**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

In [1]:
import numpy as np


1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [2]:
import numpy as np


grades = [85, 90, 78, 92, 88, 76, 95, 89]

grades_array = np.array(grades)

print(grades_array)


[85 90 78 92 88 76 95 89]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [3]:
import numpy as np


prices = [
    [12.5, 35.0, 28.0, 150.0], 
    [13.0, 34.5, 30.0, 145.0], 
    [11.8, 36.0, 27.5, 155.0]  
]

prices_matrix = np.array(prices)

print(prices_matrix)


[[ 12.5  35.   28.  150. ]
 [ 13.   34.5  30.  145. ]
 [ 11.8  36.   27.5 155. ]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [4]:
import numpy as np

grades = [85, 90, 78, 92, 88, 76, 95, 89]
grades_array = np.array(grades)

prices = [
    [12.5, 35.0, 28.0, 150.0],
    [13.0, 34.5, 30.0, 145.0],
    [11.8, 36.0, 27.5, 155.0]
]
prices_matrix = np.array(prices)

print(grades_array.dtype)
print( prices_matrix.dtype)


int64
float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
import numpy as np

grades = [85, 90, 78, 92, 88, 76, 95, 89]
grades_array = np.array(grades)

prices = [
    [12.5, 35.0, 28.0, 150.0],
    [13.0, 34.5, 30.0, 145.0],
    [11.8, 36.0, 27.5, 155.0]
]
prices_matrix = np.array(prices)

print(grades_array.shape)
print(prices_matrix.shape)


(8,)
(3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [6]:
import numpy as np

days = 7

start_profit = 0
end_profit = 1000.50

profit_array = np.linspace(start_profit, end_profit, days)

print(profit_array)


[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [7]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

horizontal_stack = np.hstack((array1, array2))

vertical_stack = np.vstack((array1, array2))

print(array1)
print(array2)
print(horizontal_stack)
print(vertical_stack)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [8]:
import numpy as np

def transpose_array(arr):

    return arr.reshape(arr.shape[1], arr.shape[0])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = transpose_array(matrix)

print(matrix)
print(transposed_matrix)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [9]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

addition = array1 + array2

subtraction = array1 - array2

scalar_multiplication = array1 * 2

elementwise_multiplication = array1 * array2

matrix_multiplication = np.dot(array1, array2)

print(array1)
print(array2)

print (addition)
print(subtraction)
print(scalar_multiplication)
print(elementwise_multiplication)
print(matrix_multiplication)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[2 4]
 [6 8]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [10]:
import numpy as np

matrix = np.array([
    [10, 25, 3],
    [7, 15, 30],
    [22, 5, 18]
])

min_value = np.min(matrix)

max_value = np.max(matrix)

sum_values = np.sum(matrix)

row_min_values = np.min(matrix, axis=1)

col_max_values = np.max(matrix, axis=0)

print(matrix)
print(min_value)
print(max_value)
print(sum_values)
print(row_min_values)
print(col_max_values)


[[10 25  3]
 [ 7 15 30]
 [22  5 18]]
3
30
135
[3 7 5]
[22 25 30]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [11]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 2, 1],
    [3, 5, 1]
])

unique_values, frequencies = np.unique(matrix, return_counts=True)

print("Матриця:\n", matrix)
print("\nУнікальні значення:", unique_values)
print("Частоти відповідних значень:", frequencies)


Матриця:
 [[1 2 3]
 [4 2 1]
 [3 5 1]]

Унікальні значення: [1 2 3 4 5]
Частоти відповідних значень: [3 2 2 1 1]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [12]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [13]:
import pandas as pd

data = [
    {'last_name': 'Ivanov', 'first_name': 'Ivan', 'birth_date': '1990-01-01', 'weight': 75, 'insurance': True},
    {'last_name': 'Petrova', 'first_name': 'Petra', 'birth_date': '1985-02-15', 'weight': 65, 'insurance': False},
    {'last_name': 'Sidorov', 'first_name': 'Sidor', 'birth_date': '1992-03-10', 'weight': None, 'insurance': True},  
    {'last_name': 'Kuznetsova', 'first_name': 'Ksenia', 'birth_date': '1988-07-20', 'weight': 70, 'insurance': True}
]

df = pd.DataFrame(data)

print("DataFrame:")
print(df)

print("\nТипи даних у кожній колонці:")
print(df.dtypes)


DataFrame:
    last_name first_name  birth_date  weight  insurance
0      Ivanov       Ivan  1990-01-01    75.0       True
1     Petrova      Petra  1985-02-15    65.0      False
2     Sidorov      Sidor  1992-03-10     NaN       True
3  Kuznetsova     Ksenia  1988-07-20    70.0       True

Типи даних у кожній колонці:
last_name      object
first_name     object
birth_date     object
weight        float64
insurance        bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [1]:
import pandas as pd 

df = pd.read_csv('missile_attacks_daily.csv')

print(df.head())

print(df.dtypes)


         time_start          time_end             model  \
0  2025-02-22 19:00  2025-02-23 08:00    Shahed-136/131   
1  2025-02-22 19:00  2025-02-23 08:00  Iskander-M/KN-23   
2  2025-02-21 19:00  2025-02-22 08:00    Shahed-136/131   
3        2025-02-22        2025-02-22            Молнія   
4        2025-02-22        2025-02-22            Lancet   

                                        launch_place   target carrier  \
0  Primorsko-Akhtarsk and Chauda, Crimea and Kurs...  Ukraine     NaN   
1                                             Crimea  Ukraine     NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...  Ukraine     NaN   
3                                                NaN    south     NaN   
4                                                NaN    south     NaN   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0     267.0      138.0           115.0                   1.0          3.0   
1       3.0        0.0             NaN              

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [2]:
import pandas as pd

df = pd.read_csv('missile_attacks_daily.csv')

print(df.head(10))


         time_start          time_end  \
0  2025-02-22 19:00  2025-02-23 08:00   
1  2025-02-22 19:00  2025-02-23 08:00   
2  2025-02-21 19:00  2025-02-22 08:00   
3        2025-02-22        2025-02-22   
4        2025-02-22        2025-02-22   
5  2025-02-20 19:00  2025-02-21 08:00   
6  2025-02-20 19:00  2025-02-21 08:00   
7        2025-02-21        2025-02-21   
8        2025-02-21        2025-02-21   
9        2025-02-20  2025-02-20 10:00   

                                         model  \
0                               Shahed-136/131   
1                             Iskander-M/KN-23   
2                               Shahed-136/131   
3                                       Молнія   
4                                       Lancet   
5                               Shahed-136/131   
6                             Iskander-M/KN-23   
7                                         ZALA   
8                                     Supercam   
9  X-101/X-555 and Kalibr and Iskander-M/KN-23  

14. Отримайте інформацію про форму датафрейму.

In [3]:
import pandas as pd

df = pd.read_csv('missile_attacks_daily.csv')

print(df.shape)


(2155, 17)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [4]:
import pandas as pd

df = pd.read_csv('missile_attacks_daily.csv')

df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2155 non-null   object 
 1   time_end              2155 non-null   object 
 2   model                 2155 non-null   object 
 3   launch_place          1082 non-null   object 
 4   target                2127 non-null   object 
 5   carrier               229 non-null    object 
 6   launched              2152 non-null   float64
 7   destroyed             2149 non-null   float64
 8   not_reach_goal        195 non-null    float64
 9   cross_border_belarus  34 non-null     float64
 10  back_russia           36 non-null     float64
 11  still_attacking       32 non-null     float64
 12  affected region       27 non-null     object 
 13  destroyed_details     329 non-null    object 
 14  launched_details      4 non-null      object 
 15  launch_place_details 

16. Отримайте статистику для колонок числового типу.

In [5]:
import pandas as pd

df = pd.read_csv('missile_attacks_daily.csv')

print(df.describe())


          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2152.000000  2149.000000      195.000000             34.000000   
mean     12.037175     8.241508       24.846154              2.264706   
std      25.138122    16.047237       22.513614              2.004674   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        5.000000              1.000000   
50%       2.000000     1.000000       19.000000              2.000000   
75%       9.000000     7.000000       39.000000              2.000000   
max     267.000000   138.000000      115.000000             10.000000   

       back_russia  still_attacking  
count    36.000000        32.000000  
mean      2.027778         2.687500  
std       1.133543         2.775904  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         3.250000  
max       5.000000        10.000000  


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [6]:
import pandas as pd

df = pd.read_csv('missile_attacks_daily.csv')

unique_counts = df.nunique()

column_with_fewest_unique = unique_counts.idxmin()

value_counts = df[column_with_fewest_unique].value_counts()

print(f"Колонка з найменшою кількістю унікальних значень: {column_with_fewest_unique}")
print(value_counts)


Колонка з найменшою кількістю унікальних значень: launched_details
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Пункт списку
2.   Пункт списку

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [8]:

df['launched'] = df['launched'].astype('Int64')

print(df['launched'].dtype)

print(df['launched'].head())



Int64
0    267
1      3
2    162
3      1
4      1
Name: launched, dtype: Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [9]:

threshold = 0.3 * len(df) 

df_cleaned = df.dropna(thresh=threshold, axis=1)

print(df_cleaned.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   time_start    2155 non-null   object 
 1   time_end      2155 non-null   object 
 2   model         2155 non-null   object 
 3   launch_place  1082 non-null   object 
 4   target        2127 non-null   object 
 5   launched      2152 non-null   Int64  
 6   destroyed     2149 non-null   float64
 7   source        2155 non-null   object 
dtypes: Int64(1), float64(1), object(6)
memory usage: 136.9+ KB
None


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [12]:

print(df.columns)


df['time_start'] = pd.to_datetime(df['time_start'], errors='coerce')
df['time_end'] = pd.to_datetime(df['time_end'], errors='coerce')

df['duration'] = (df['time_end'] - df['time_start']).dt.total_seconds() / 3600  

df_cleaned = df.drop_duplicates()

df_cleaned = df_cleaned[df_cleaned['duration'] > 0]

df_cleaned.reset_index(drop=True, inplace=True)

rows_deleted = len(df) - len(df_cleaned)
print(f"Кількість видалених рядків: {rows_deleted}")

print(df_cleaned.info())




Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'carrier',
       'launched', 'destroyed', 'not_reach_goal', 'cross_border_belarus',
       'back_russia', 'still_attacking', 'affected region',
       'destroyed_details', 'launched_details', 'launch_place_details',
       'source'],
      dtype='object')
Кількість видалених рядків: 1667
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488 entries, 0 to 487
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   time_start            488 non-null    datetime64[ns]
 1   time_end              488 non-null    datetime64[ns]
 2   model                 488 non-null    object        
 3   launch_place          374 non-null    object        
 4   target                479 non-null    object        
 5   carrier               95 non-null     object        
 6   launched              488 non-null    Int64         
 7   destroyed 

**місце для текстової відповіді**

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [13]:

df[df.isnull().any(axis=1)]


time_start            time_end               model  \
0    2025-02-22 19:00:00 2025-02-23 08:00:00      Shahed-136/131   
1    2025-02-22 19:00:00 2025-02-23 08:00:00    Iskander-M/KN-23   
2    2025-02-21 19:00:00 2025-02-22 08:00:00      Shahed-136/131   
3                    NaT                 NaT              Молнія   
4                    NaT                 NaT              Lancet   
...                  ...                 ...                 ...   
2150 2022-10-01 12:00:00 2022-10-01 12:00:00            Orlan-10   
2151                 NaT                 NaT            Orlan-10   
2152 2022-09-29 23:00:00 2022-09-29 23:59:00      Shahed-136/131   
2153                 NaT                 NaT                X-59   
2154                 NaT                 NaT  Reconnaissance UAV   

                                           launch_place  \
0     Primorsko-Akhtarsk and Chauda, Crimea and Kurs...   
1                                                Crimea   
2     Primorsko-Akhtarsk and Kursk oblast and Bryans...   
3                                                   NaN   
4                                                   NaN   
...                                                 ...   
2150                                                NaN   
2151                                                NaN   
2152                                                NaN   
2153                                                NaN   
2154                                                NaN   

                                             target carrier  launched  \
0                                           Ukraine     NaN       267   
1                                           Ukraine     NaN         3   
2                                           Ukraine     NaN       162   
3                                             south     NaN         1   
4                                             south     NaN         1   
...                                             ...     ...       ...   
2150                                        Ukraine     NaN         1   
2151                                        Ukraine     NaN         3   
2152               Odesa oblast and Mykolaiv oblast     NaN         7   
2153  Dnipropetrovsk oblast and Zaporizhzhia oblast   Su-35         5   
2154                                        Ukraine     NaN         3   

      destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0         138.0           115.0                   1.0          3.0   
1           0.0             NaN                   NaN          NaN   
2          82.0            75.0                   NaN          NaN   
3           1.0             NaN                   NaN          NaN   
4           1.0             NaN                   NaN          NaN   
...         ...             ...                   ...          ...   
2150        1.0             NaN                   NaN          NaN   
2151        3.0             NaN                   NaN          NaN   
2152        5.0             NaN                   NaN          NaN   
2153        4.0             NaN                   NaN          NaN   
2154        3.0             NaN                   NaN          NaN   

      still_attacking                                    affected region  \
0                 NaN  ['Kyiv oblast', 'Poltava oblast', 'Odesa oblas...   
1                 NaN                                                NaN   
2                 NaN  ['Kyiv oblast', 'Kharkiv oblast', 'Kirovohrad ...   
3                 NaN                                                NaN   
4                 NaN                                                NaN   
...               ...                                                ...   
2150              NaN                                                NaN   
2151              NaN                                                NaN   
2152              NaN                                                NaN   
2153      